language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: salvadormg
	on: master
	skik_cleanup: true
	api_key:
		secure: O/R03g8hwyPpqqNzEfWkYYmpZ7WDquf5U5lxrSgiKDCnJnHhOwXH6N+siGpUAioqIQUN712C+aF//1ZQx5BK4+0AgZFq/8ZdcwRdrIqEVRvjxWAAwHf/dhbkGrk6Fuxrmi09y/sPRnPGy4VgrR/uOmpYlG0sqFFreTcKQulzgJufzuTpCYIDVf7lwLpDvIbbd41REhCp9j97PlqogbMvWcEGNTeqv/h3VVvJuMnjLSYDpAZfLaBJX+BnCj5UYgPlf0VEGmlcInekUiFeBthK/0vtmtz40iL9NG/O0rt0MGmF5OdTxJ59zAjKnJtMD3iORfQZQ8BLJLvlUvV8BxHKCIxMqupFlYuiy4AAY3WI3zCcoXakQYxk0qsOT/C5oZmlsgE2IXcCZt8cHnvvfOTSgAP7emJa2nG4VD0jIkNqOc+LEp+ahFheEsRvMbMEwYBCZbYw6C9O5pl39PrMOjm+tAoPXNKc0r3ki11mcOsZnzAlAoSWYhkPzfrq2Piu50pJq0zW0N+8/43NaHE6zQJ5JpmzvRRQQsGLX6Dq+oA30f8+J8jgMu/8Y/qJeTWivJB7NXHym61tGU+242em1T4e9IOtN9tHjDuuulhqTpOeT8W8JInk28hwboQAJW9lQNXYjwcIzVMdJGx/x0afABn7gebNFclBWzQSIfHSmurLTaQ=
